import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div>Next.js + keycloak</div>
        <div className={styles.authButtons}>
          <button>Profile</button>
          <button>Logout</button>
          <button>My Account</button>
        </div>
      </header>

      <main className={styles.main}></main>

      <footer className={styles.footer}>Powered by Me</footer>
    </div>
  );
};

export default Home;
